version: "3"

services:
  homepage:
    container_name: homepage
    build:
      context: ./homepage
      dockerfile: build/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    working_dir: /app
    volumes:
      - ./homepage:/app
      - ${DRIVE_ENTRYPOINT}:/mnt/ssd1

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
      - ${DRIVE_ENTRYPOINT}:/srv
    ports:
      - "8080:8080"

  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ./transmission:/config
      - /etc/openvpn/${TRANSMISSION_OPENVPN_PROVIDER_VOL}:/etc/openvpn/custom/
      - ${DRIVE_ENTRYPOINT}/DOWNLOADS/Transmission:/data
    ports:
      - "9091:9091"
    environment:
      - OPENVPN_PROVIDER=${TRANSMISSION_OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${TRANSMISSION_OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${TRANSMISSION_OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${TRANSMISSION_OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${TRANSMISSION_LOCAL_NETWORK},${TRANSMISSION_PIVPN_NETWORK}

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./plex/config:/config
      - ${DRIVE_ENTRYPOINT}/MOVIES:/movies
      - ${DRIVE_ENTRYPOINT}/SHOWS:/shows
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    volumes:
      - ./overseerr/config:/config
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - ./radarr:/config
      - ${DRIVE_ENTRYPOINT}/MOVIES:/movies
      - ${DRIVE_ENTRYPOINT}/DOWNLOADS/Transmission:/data
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - ./sonarr:/config
      - ${DRIVE_ENTRYPOINT}/SHOWS:/shows
      - ${DRIVE_ENTRYPOINT}/DOWNLOADS/Transmission:/data
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    volumes:
      - ./bazarr:/config
      - ${DRIVE_ENTRYPOINT}:/data
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    volumes:
      - ./prowlarr:/config
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
