version: "3"

services:
  startpage:
    container_name: startpage
    image: python:3
    restart: on-failure
    volumes:
      - ./startpage:/app
    ports:
      - "80:80"
    working_dir: /app
    command: python3 -m http.server 80

  pairdrop:
    container_name: pairdrop
    image: lscr.io/linuxserver/pairdrop:latest
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - DONATION_BUTTON_ACTIVE=false
      - TWITTER_BUTTON_ACTIVE=false
      - MASTODON_BUTTON_ACTIVE=false
      - BLUESKY_BUTTON_ACTIVE=false
      - CUSTOM_BUTTON_ACTIVE=false
      - PRIVACYPOLICY_BUTTON_ACTIVE=false

  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    network_mode: host
    restart: on-failure
    volumes:
      - ./homeassistant:/config
    ports:
      - "8123:8123"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
      - ${DRIVE_ENTRYPOINT}/usr:/srv
    ports:
      - "8080:8080"

  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    restart: on-failure
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ./transmission:/config
      - /etc/openvpn/${TRANSMISSION_OPENVPN_PROVIDER_VOL}:/etc/openvpn/custom/
      - ${DRIVE_ENTRYPOINT}/tmp/transmission-data:/data
    ports:
      - "9091:9091"
    environment:
      - OPENVPN_PROVIDER=${TRANSMISSION_OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${TRANSMISSION_OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${TRANSMISSION_OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${TRANSMISSION_OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${TRANSMISSION_LOCAL_NETWORK},${TRANSMISSION_PIVPN_NETWORK}

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: on-failure
    network_mode: "host"
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ${DRIVE_ENTRYPOINT}/usr/local:/local
      - ${DRIVE_ENTRYPOINT}/usr/remote:/remote
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - VERSION=docker

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: on-failure
    volumes:
      - ./overseerr/config:/config
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: on-failure
    volumes:
      - ./radarr:/config
      - ${DRIVE_ENTRYPOINT}/usr/remote:/remote
      - ${DRIVE_ENTRYPOINT}/tmp/transmission-data:/data
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: on-failure
    volumes:
      - ./sonarr:/config
      - ${DRIVE_ENTRYPOINT}/usr/remote:/remote
      - ${DRIVE_ENTRYPOINT}/tmp/transmission-data:/data
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: on-failure
    volumes:
      - ./bazarr:/config
      - ${DRIVE_ENTRYPOINT}/usr/remote:/remote
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: on-failure
    volumes:
      - ./prowlarr:/config
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
