version: "3"

services:
  startpage:
    container_name: startpage
    image: python:3
    restart: unless-stopped
    volumes:
      - ./startpage:/app
    ports:
      - "80:80"
    working_dir: /app
    command: python3 -m http.server 80

  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./homeassistant:/config
    ports:
      - "8123:8123"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
      - ${DRIVE_ENTRYPOINT}/usr:/srv
    ports:
      - "8080:8080"

  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ./transmission:/config
      - /etc/openvpn/mullvad:/etc/openvpn/custom/
      - ${DRIVE_ENTRYPOINT}/tmp/transmission-data:/data
    ports:
      - "9091:9091"
    environment:
      - OPENVPN_PROVIDER=-
      - OPENVPN_CONFIG=-
      - OPENVPN_USERNAME=-
      - OPENVPN_PASSWORD=-
      - LOCAL_NETWORK=<LOCAL_IP>,<PIVPN_IP>

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ${DRIVE_ENTRYPOINT}/usr/videos:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - VERSION=docker

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    volumes:
      - ./overseerr/config:/config
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - ./radarr:/config
      - ${DRIVE_ENTRYPOINT}/usr/videos/movies:/media
      - ${DRIVE_ENTRYPOINT}/tmp/transmission-data:/data
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - ./sonarr:/config
      - ${DRIVE_ENTRYPOINT}/usr/videos/shows:/media
      - ${DRIVE_ENTRYPOINT}/tmp/transmission-data:/data
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    volumes:
      - ./prowlarr:/config
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
